// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8EzeL_owelRYpZQLUhcRq65loJbC72tg',
    appId: '1:730840197111:web:20eaf428b7b40336ec70f2',
    messagingSenderId: '730840197111',
    projectId: 'huggo-test-10fc7',
    authDomain: 'huggo-test-10fc7.firebaseapp.com',
    databaseURL: 'https://huggo-test-10fc7-default-rtdb.firebaseio.com',
    storageBucket: 'huggo-test-10fc7.appspot.com',
    measurementId: 'G-6DV543WWVR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXY9hktMC2Oq9x-e75uilAK8Hmcv7ThGU',
    appId: '1:730840197111:android:517d9a7b84bc8058ec70f2',
    messagingSenderId: '730840197111',
    projectId: 'huggo-test-10fc7',
    databaseURL: 'https://huggo-test-10fc7-default-rtdb.firebaseio.com',
    storageBucket: 'huggo-test-10fc7.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6ThHSEzEkFrCHB_BisHIkAx0ZUrz736I',
    appId: '1:730840197111:ios:4750b57a93416188ec70f2',
    messagingSenderId: '730840197111',
    projectId: 'huggo-test-10fc7',
    databaseURL: 'https://huggo-test-10fc7-default-rtdb.firebaseio.com',
    storageBucket: 'huggo-test-10fc7.appspot.com',
    androidClientId: '730840197111-iu2q48b5ptk4kqmc64i1epbugt3cdg81.apps.googleusercontent.com',
    iosClientId: '730840197111-ck3r3tprv3d40fvp02draimgdaiq7kgj.apps.googleusercontent.com',
    iosBundleId: 'com.example.diaryfinalapp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6ThHSEzEkFrCHB_BisHIkAx0ZUrz736I',
    appId: '1:730840197111:ios:4750b57a93416188ec70f2',
    messagingSenderId: '730840197111',
    projectId: 'huggo-test-10fc7',
    databaseURL: 'https://huggo-test-10fc7-default-rtdb.firebaseio.com',
    storageBucket: 'huggo-test-10fc7.appspot.com',
    androidClientId: '730840197111-iu2q48b5ptk4kqmc64i1epbugt3cdg81.apps.googleusercontent.com',
    iosClientId: '730840197111-ck3r3tprv3d40fvp02draimgdaiq7kgj.apps.googleusercontent.com',
    iosBundleId: 'com.example.diaryfinalapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8EzeL_owelRYpZQLUhcRq65loJbC72tg',
    appId: '1:730840197111:web:7eb181b35930637dec70f2',
    messagingSenderId: '730840197111',
    projectId: 'huggo-test-10fc7',
    authDomain: 'huggo-test-10fc7.firebaseapp.com',
    databaseURL: 'https://huggo-test-10fc7-default-rtdb.firebaseio.com',
    storageBucket: 'huggo-test-10fc7.appspot.com',
    measurementId: 'G-4B49FQTYY6',
  );

}