name: diaryapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  auth0_flutter: ^1.7.2
  flutter_dotenv: ^5.1.0
  sqflite: ^2.3.3+1
  path: ^1.9.0
  google_fonts: ^4.0.4
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
