// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8EzeL_owelRYpZQLUhcRq65loJbC72tg',
    appId: '1:730840197111:web:20eaf428b7b40336ec70f2',
    messagingSenderId: '730840197111',
    projectId: 'huggo-test-10fc7',
    authDomain: 'huggo-test-10fc7.firebaseapp.com',
    databaseURL: 'https://huggo-test-10fc7-default-rtdb.firebaseio.com',
    storageBucket: 'huggo-test-10fc7.appspot.com',
    measurementId: 'G-6DV543WWVR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXY9hktMC2Oq9x-e75uilAK8Hmcv7ThGU',
    appId: '1:730840197111:android:ee97fd8883e0c06dec70f2',
    messagingSenderId: '730840197111',
    projectId: 'huggo-test-10fc7',
    databaseURL: 'https://huggo-test-10fc7-default-rtdb.firebaseio.com',
    storageBucket: 'huggo-test-10fc7.appspot.com',
  );
}
